// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package auditory

const (
	Version     = "v0.9.8"
	GitCommit   = "9eef250"          // the commit JUST BEFORE the release
	VersionDate = "2021-10-22 09:54" // UTC
)
